source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin', '~> 0.3.1'
gem 'sinatra-activerecord'

gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'rake'
gem 'ridgepole'
gem 'puma'

group :development do
  gem 'rubocop'
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'awesome_print'
end

group :test do
  gem 'rspec'
end


